### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by avi-gitkraken**

### CODE REVIEW

**Comment by avi-gitkraken** [comment]
1

**Comment by avi-gitkraken** [comment]
2

**Comment by avi-gitkraken** [comment]
3

**Comment by avi-gitkraken** [comment]
4

**Review by avi-moskoff — CHANGES_REQUESTED** [review]
fsv

**Comment by avi-gitkraken** [comment]
Hey @avi-gitkraken, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #12**](https://dev.gitkraken.dev/drafts/f3e421fa-a55f-44cd-9807-e9a54c692421?source=PRComment)
>https://github.com/avi-gitkraken/dummy-repo-123/pull/12

You can also review and apply these suggestions [locally on your machine](https://dev.gitkraken.dev/link/drafts/f3e421fa-a55f-44cd-9807-e9a54c692421).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://www.gitkraken.com/solutions/code-suggest) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.com) to speed up PR review._
</details>

**Pull request closed without merging**
